dataset_name: SHT
rgb_dataset_path: ../../zwh/Datasets/SHT_Frames.h5
flow_dataset_path: ../datasets/SHT_Flows.h5
train_split: data/SH_Train_new.txt
test_split: data/SH_Test_NEW.txt
pseudo_labels: ../WVAD/data/SHT_I3D_PLs.npy
# pseudo_labels: data/train_results.npy

test_mask_dir: ../WVAD/data/test_frame_mask/

feature_dim: 512
epochs: 801
warmup_epochs: 5
eval_epoch: 15
batch_size: 3     # 5 10
gpu0sz: 0.6      #0.6 0.8
test_batch_size: 20     # 20 42
clips_num: 8
segment_len: 16
ten_crop: False

# model parameters
pretrained: True
rgb_pretrained_model_path: ../WVAD/pretrained/C3D_Sport1M.pth
flow_pretrained_model_path: ../WVAD/pretrained/model_flow.pth

stored_path: stored_models/SHT_I3D_AUC_0.9483.pth
freeze_backbone: True
freeze_blocks: [conv3d_1a_7x7,conv3d_2b_1x1,conv3d_2c_3x3,mixed_3b,mixed_3c,mixed_4b,mixed_4c,mixed_4d,mixed_4e,mixed_4f,mixed_5b,mixed_5c]
freeze_epochs: 0    # 30
dropout_rate: 0.8
expand_k: 8

# loss parameters
class_reweights: [0.8,0.65]
label_smoothing: 0
loss_margin: 100
loss_alpha: 0.0001
accumulate_step: 3   # 3
grad_clip: 20

# optimizer
optimizer: Adam
optimizer_args: {lr: 0.0001, weight_decay: 0.0005, lr_scheduler: None, betas: [0.9, 0.999]}

save_path: ./save/c3d_nocrop


