rgb_list: data/rtfm/list/shanghai-i3d-train-10crop2.list
test_rgb_list: data/rtfm/list/shanghai-i3d-test-10crop2.list


gt: data/rtfm/list/gt-sh.npy

feature_size: 2048
max_epoch: 15000
eval_epoch: 30
batch_size: 32

# optimizer
optimizer: Adam
optimizer_args: {lr: 0.001, weight_decay: 0.005, lr_scheduler: None, betas: [0.9, 0.999]}

save_path: ./save/rtfm/


