rgb_list: data/rtfm/list/shanghai-i3d-train-10crop2.list
test_rgb_list: data/rtfm/list/shanghai-i3d-test-10crop2.list
rgb_file_path: ../AllDatasets/ShanghaiTech/features/SHT_rgb_fea.h5
flow_file_path: ../AllDatasets/ShanghaiTech/features/SHT_flow_fea.h5
train_split: data/SH_Train_new.txt
test_split: data/SH_Test_NEW.txt
test_mask_dir: data/test_frame_mask/

gt: data/rtfm/list/gt-sh.npy

segment_len: 16
feature_size: 2048
max_epoch: 15000
eval_epoch: 5
batch_size: 32

# optimizer
optimizer: Adam
optimizer_args: {lr: 0.001, weight_decay: 0.005, lr_scheduler: None, betas: [0.9, 0.999]}

save_path: ./save/hard/


